"""
Hybrid Spike-Continuous Encoding

Combines the sparsity and energy efficiency of spiking neural networks
with the differentiability of continuous-value networks.

References:
- Mostafa, H. (2017). Supervised learning based on temporal coding in spiking neural networks.
- Comsa, I. M., et al. (2022). Temporal coding in spiking neural networks with alpha synaptic function.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F


class TTFSEncoder(nn.Module):
    """
    Time-to-First-Spike (TTFS) Encoder.
    
    Encodes continuous values as spike times.
    Larger values → earlier spikes (smaller time values).
    
    This is differentiable using a relaxed version.
    """
    def __init__(self, d_in, d_out, max_time=10.0, tau_syn=1.0):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.max_time = max_time
        self.tau_syn = tau_syn
        
        self.linear = nn.Linear(d_in, d_out, bias=True)
        nn.init.xavier_uniform_(self.linear.weight)
        nn.init.zeros_(self.linear.bias)
    
    def forward(self, x):
        """
        Args:
            x: (batch, seq_len, d_in) - continuous input
        Returns:
            spike_times: (batch, seq_len, d_out) - pseudo spike times
            spike_probs: (batch, seq_len, d_out) - probability of spiking
        """
        # Linear projection
        z = self.linear(x)
        
        # Convert to spike time: higher activation → earlier spike
        # Use sigmoid to map to (0, max_time)
        spike_probs = torch.sigmoid(z)
        
        # Inverse relationship: strong activation → small time
        # Add small epsilon to avoid division by zero
        spike_times = self.max_time * (1.0 - spike_probs) + 1e-4
        
        return spike_times, spike_probs
    
    def decode(self, spike_times, spike_probs):
        """
        Decode TTFS representation back to continuous values.
        """
        # Earlier spikes = higher values
        values = (self.max_time - spike_times) / self.max_time
        values = values * spike_probs  # Only active if spike occurred
        return values


class SpikingSynapse(nn.Module):
    """
    Alpha synaptic function for spike transmission.
    
    Models the postsynaptic potential (PSP) generated by incoming spikes.
    """
    def __init__(self, tau=2.0):
        super().__init__()
        self.tau = tau
    
    def forward(self, spikes, dt=1.0):
        """
        Args:
            spikes: (batch, seq_len, d) binary spike train
            dt: time step
        Returns:
            psp: postsynaptic potentials
        """
        # Exponential decay of synaptic current
        # I(t+1) = (1 - dt/tau) * I(t) + spikes(t)
        batch, seq_len, d = spikes.shape
        device = spikes.device
        
        psp = torch.zeros(batch, d, device=device)
        psp_trace = []
        
        for t in range(seq_len):
            psp = (1.0 - dt / self.tau) * psp + spikes[:, t, :]
            psp_trace.append(psp)
        
        psp_trace = torch.stack(psp_trace, dim=1)  # (batch, seq_len, d)
        return psp_trace


class HybridSpikeEncoder(nn.Module):
    """
    Hybrid encoder that combines continuous and spike representations.
    
    Maintains both:
    - Continuous value representation (for gradient flow)
    - Spike representation (for sparsity and efficiency)
    
    The two representations are coupled through shared latent space.
    """
    def __init__(
        self,
        d_model,
        spike_dim_ratio=0.5,
        max_time=10.0,
        tau_syn=2.0,
        threshold=0.5,
    ):
        super().__init__()
        self.d_model = d_model
        self.spike_dim = int(d_model * spike_dim_ratio)
        self.cont_dim = d_model - self.spike_dim
        self.max_time = max_time
        
        # Continuous path
        self.cont_proj = nn.Linear(d_model, self.cont_dim)
        
        # Spike path
        self.ttfs = TTFSEncoder(d_model, self.spike_dim, max_time=max_time)
        self.synapse = SpikingSynapse(tau=tau_syn)
        self.spike_threshold = threshold
        
        # Fusion: combine continuous and spike back to d_model
        self.fusion = nn.Linear(d_model, d_model)
        self.norm = nn.LayerNorm(d_model)
    
    def forward(self, x):
        """
        Args:
            x: (batch, seq_len, d_model)
        Returns:
            out: (batch, seq_len, d_model) hybrid representation
            spike_info: dict with spike times, probs, rates
        """
        batch, seq_len, d = x.shape
        
        # Continuous path
        cont = self.cont_proj(x)  # (batch, seq_len, cont_dim)
        
        # Spike path: encode to TTFS
        spike_times, spike_probs = self.ttfs(x)
        
        # Convert to binary spike train (relaxed for differentiability)
        # In training, use soft spikes; in eval, can use hard spikes
        if self.training:
            soft_spikes = spike_probs  # Use probabilities as soft spikes
        else:
            soft_spikes = (spike_probs > self.spike_threshold).float()
        
        # Apply synaptic filtering
        spike_psp = self.synapse(soft_spikes)  # (batch, seq_len, spike_dim)
        
        # Combine
        hybrid = torch.cat([cont, spike_psp], dim=-1)  # (batch, seq_len, d_model)
        
        # Fusion and normalization
        out = self.fusion(hybrid)
        out = self.norm(out)
        
        # Spike statistics for regularization
        spike_rate = soft_spikes.mean().item()
        
        spike_info = {
            'spike_times': spike_times,
            'spike_probs': spike_probs,
            'spike_rate': spike_rate,
            'soft_spikes': soft_spikes,
        }
        
        return out, spike_info


class SpikeGatedLinear(nn.Module):
    """
    Linear layer gated by spike signals.
    
    Only a subset of connections are active based on spike input,
    providing structured sparsity.
    """
    def __init__(self, d_in, d_out, sparsity_target=0.3):
        super().__init__()
        self.d_in = d_in
        self.d_out = d_out
        self.sparsity_target = sparsity_target
        
        self.weight = nn.Parameter(torch.randn(d_out, d_in) * 0.02)
        self.bias = nn.Parameter(torch.zeros(d_out))
        
        # Gating mechanism
        self.gate = nn.Linear(d_in, d_out, bias=True)
        nn.init.zeros_(self.gate.weight)
        nn.init.constant_(self.gate.bias, -1.0)  # Start mostly closed
    
    def forward(self, x, spike_gate=None):
        """
        Args:
            x: (batch, seq_len, d_in)
            spike_gate: optional external spike signal
        Returns:
            out: (batch, seq_len, d_out)
        """
        # Compute gate
        if spike_gate is not None:
            gate = spike_gate
        else:
            gate = torch.sigmoid(self.gate(x))
        
        # Standard linear projection
        out = F.linear(x, self.weight, self.bias)
        
        # Apply gate
        out = out * gate
        
        return out, gate
